# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  batch: true
  tags:
    include:
      - '2.*'
  branches:
    include:
      - develop

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

name: NHSISINFORMATIONALCMS_$(SourceBranchName)_$(Date:yyyyMMdd)_$(Rev:.r)

stages:
- stage: Archive
  displayName: Zip files
  jobs:
  - job: Archive
    displayName: Zip and Archive
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/nhs-is-informatinal-cms-build.zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/nhs-is-informatinal-cms-build.zip'
        ArtifactName: 'nhs_is_informational_cms'
        publishLocation: 'Container'