# Generated by Django 4.1.5 on 2023-01-30 10:23

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.blocks
import wagtail.contrib.routable_page.models
import wagtail.contrib.typed_table_block.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtailmetadata.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtailcore', '0078_referenceindex'),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.StreamField([('fixed', wagtail.blocks.StructBlock([('background_color', wagtail.blocks.ChoiceBlock(choices=[('default', 'Default'), ('white', 'White')])), ('column', wagtail.blocks.ChoiceBlock(choices=[('full', 'Full width'), ('one-half', 'One half'), ('one-third', 'One third'), ('two-thirds', 'Two thirds')])), ('content', wagtail.blocks.StreamBlock([('inset_text', wagtail.blocks.StructBlock([('body', wagtail.blocks.RichTextBlock(required=True))], group='Text')), ('rich_text', wagtail.blocks.RichTextBlock(group='Text')), ('action_link', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(label='Link text', required=True)), ('external_url', wagtail.blocks.URLBlock(label='URL', required=False)), ('new_window', wagtail.blocks.BooleanBlock(label='Open in new window', required=False)), ('internal_page', wagtail.blocks.PageChooserBlock(label='Internal Page', required=False))], group='Buttons and Links')), ('button_link', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(label='Link text', required=True)), ('internal_page', wagtail.blocks.PageChooserBlock(label='Internal Page', required=True))], group='Buttons and Links')), ('table', wagtail.contrib.typed_table_block.blocks.TypedTableBlock([('rich_text', wagtail.blocks.RichTextBlock())], group='Components')), ('card_group', wagtail.blocks.StructBlock([('column', wagtail.blocks.ChoiceBlock(choices=[('', 'Full-width'), ('one-half', 'One-half'), ('one-third', 'One-third')], required=False)), ('body', wagtail.blocks.StreamBlock([('card_basic', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(required=True)), ('heading_level', wagtail.blocks.IntegerBlock(default=3, help_text='The heading level affects users with screen readers. Ignore this if there is no label. Default=3, Min=2, Max=6.', max_value=6, min_value=2)), ('heading_size', wagtail.blocks.ChoiceBlock(choices=[('', 'Default'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], help_text="The heading size affects the visual size, this follows the front-end library's sizing.", required=False)), ('body', wagtail.blocks.RichTextBlock(required=False))])), ('card_clickable', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(required=True)), ('heading_level', wagtail.blocks.IntegerBlock(default=3, help_text='The heading level affects users with screen readers. Ignore this if there is no label. Default=3, Min=2, Max=6.', max_value=6, min_value=2)), ('heading_size', wagtail.blocks.ChoiceBlock(choices=[('', 'Default'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], help_text="The heading size affects the visual size, this follows the front-end library's sizing.", required=False)), ('body', wagtail.blocks.RichTextBlock(required=False)), ('internal_page', wagtail.blocks.PageChooserBlock(help_text='Interal Page Link for the card', label='Internal Page', required=False)), ('url', wagtail.blocks.URLBlock(help_text='External Link for the card', label='URL', required=False))])), ('card_image', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(required=True)), ('heading_level', wagtail.blocks.IntegerBlock(default=3, help_text='The heading level affects users with screen readers. Ignore this if there is no label. Default=3, Min=2, Max=6.', max_value=6, min_value=2)), ('heading_size', wagtail.blocks.ChoiceBlock(choices=[('', 'Default'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], help_text="The heading size affects the visual size, this follows the front-end library's sizing.", required=False)), ('body', wagtail.blocks.RichTextBlock(required=False)), ('content_image', wagtail.images.blocks.ImageChooserBlock(label='Image', required=True)), ('alt_text', wagtail.blocks.CharBlock(required=True)), ('url', wagtail.blocks.URLBlock(help_text='Optional, if there is a link the entire card will be clickable.', label='URL', required=False)), ('internal_page', wagtail.blocks.PageChooserBlock(help_text='Optional, if there is a link the entire card will be clickable.', label='Internal Page', required=False))])), ('card_feature', wagtail.blocks.StructBlock([('feature_heading', wagtail.blocks.CharBlock(required=True)), ('heading_level', wagtail.blocks.IntegerBlock(default=3, help_text='The heading level affects users with screen readers. Ignore this if there is no label. Default=3, Min=2, Max=6.', max_value=6, min_value=2)), ('heading_size', wagtail.blocks.ChoiceBlock(choices=[('', 'Default'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], help_text="The heading size affects the visual size, this follows the front-end library's sizing.", required=False)), ('body', wagtail.blocks.RichTextBlock(required=True))]))], required=True))], group='Components', label='NHS Cards')), ('icon_text_card_group', wagtail.blocks.StructBlock([('column', wagtail.blocks.ChoiceBlock(choices=[('full', 'Full width'), ('one-half', 'One half'), ('one-third', 'One third')])), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.blocks.ChoiceBlock(choices=[('success', 'Success icon'), ('error', 'Error icon')], required=False)), ('text', wagtail.blocks.TextBlock(required=True))], icon='arrow-right')))], group='Components', label='Icon text cards')), ('vertical_stepper', wagtail.blocks.StructBlock([('steps', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=100, required=True)), ('text', wagtail.blocks.TextBlock(required=True))])))], group='Components', label='Vertical stepper')), ('banner', wagtail.blocks.StructBlock([('banner_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(label='Title', required=True)), ('supporting_text', wagtail.blocks.CharBlock(label='Supporting text', required=False)), ('call_to_action_label', wagtail.blocks.CharBlock(required=False)), ('call_to_action_page', wagtail.blocks.PageChooserBlock(required=False)), ('banner_height', wagtail.blocks.IntegerBlock(help_text='Choose a numeric value in pixels. If empty, height will default to the chosen image height', required=False)), ('layout', wagtail.blocks.ChoiceBlock(choices=[('title-text', 'Title - Text'), ('text-title', 'Text - Title')])), ('alignment', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('center', 'Center')]))], group='Images')), ('image_gallery', wagtail.blocks.StructBlock([('columns', wagtail.blocks.ChoiceBlock(choices=[(2, 2), (3, 3), (4, 4)], help_text='Choose the number of columns to show on each row (when viewing in desktop size.')), ('row_height', wagtail.blocks.IntegerBlock(help_text='Choose a numeric value in pixels.', required=False)), ('gallery', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('column_span', wagtail.blocks.ChoiceBlock(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('url', wagtail.blocks.URLBlock(required=False))])))], group='Images'))], blank=True, collapsed=True, null=True, use_json_field=True))], icon='resubmit', label='Fixed layout')), ('fluid', wagtail.blocks.StructBlock([('background_color', wagtail.blocks.ChoiceBlock(choices=[('default', 'Default'), ('white', 'White')])), ('content', wagtail.blocks.StreamBlock([('banner', wagtail.blocks.StructBlock([('banner_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(label='Title', required=True)), ('supporting_text', wagtail.blocks.CharBlock(label='Supporting text', required=False)), ('call_to_action_label', wagtail.blocks.CharBlock(required=False)), ('call_to_action_page', wagtail.blocks.PageChooserBlock(required=False)), ('banner_height', wagtail.blocks.IntegerBlock(help_text='Choose a numeric value in pixels. If empty, height will default to the chosen image height', required=False)), ('layout', wagtail.blocks.ChoiceBlock(choices=[('title-text', 'Title - Text'), ('text-title', 'Text - Title')])), ('alignment', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('center', 'Center')]))], group='Images'))], blank=True, collapsed=True, null=True, use_json_field=True))], icon='resubmit', label='Fluid layout'))], blank=True, null=True, use_json_field=True)),
            ],
            options={
                'verbose_name': 'News detail page',
                'verbose_name_plural': 'News detail pages',
            },
            bases=(wagtailmetadata.models.WagtailImageMetadataMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='NewsTypeSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='A slug to identify news by this type', populate_from='title')),
            ],
            options={
                'verbose_name': 'News type',
                'verbose_name_plural': 'News types',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.RichTextField(blank=True)),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image')),
            ],
            options={
                'verbose_name': 'News index page',
                'verbose_name_plural': 'News index pages',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, wagtailmetadata.models.WagtailImageMetadataMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='NewsDetailPageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='news.newsdetailpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='newsdetailpage',
            name='news_type',
            field=modelcluster.fields.ParentalManyToManyField(to='news.newstypesnippet'),
        ),
        migrations.AddField(
            model_name='newsdetailpage',
            name='search_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image'),
        ),
        migrations.AddField(
            model_name='newsdetailpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='news.NewsDetailPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
