# Generated by Django 4.1.13 on 2024-01-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SchedulerHistoryModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STARTED", "Started"),
                            ("COMPLETED", "Completed"),
                            ("ERROR", "Error"),
                            ("TIMEOUT", "Timeout"),
                        ],
                        default="STARTED",
                        max_length=25,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Scheduler History",
                "verbose_name_plural": "Scheduler History",
                "db_table": "scheduler_history_model",
            },
        ),
    ]
